### PR TITLE
Basic level & Quality of Life file Directory Improvs

### PR DESCRIPTION
**Pull request by auxfuse**
### This PR includes:
* Level 1 basic layout (more static assets need to be added if we have time later)
* level-1.html file with default boilerplate
* level1.js file with level generation/character movement/asset loading/level mechanics
* Custom background for the level
* Custom audio for the level
* Main-menu.html sync-up with merge to index.html and subsequent removal of file
* Small href update on credits.html file
* Tileset folder directory re-structured with multiple unused assets removed
* Updated gitignore file
* Removal of vsCode folder from repo directory
* main.js file updates to handle Character Sprite selection, passing from main.js - level1.js via localStorage

Big thanks for all your help with this. Especially for being patient and sitting in calls with me and listening to me ramble on 🤣 

This PR satisfies several issues:
* #11 
* #17 
* #18 
* #19 (some basic code and file directory structuring)

***

Giphy of level:

7a1a999cd28346abd6aafcb95c0d5fac

### CODE REVIEW

**Comment by AideenM12** [comment]
LGTM

**Review by CraigThomasson — COMMENTED** [review]
html and css LGTM
looked over js but was not confident I could spot issues.

**Review by AideenM12 — COMMENTED** [review]
LGTM

**Review by AideenM12 — APPROVED** [review]
LGTM

**Review by charliehawley — APPROVED** [review]
LGTM 💯

**Pull request merged**
